import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const airbnbCereal = localFont({
  variable: '--font-airbnb-cereal',
  src: "../public/fonts/AirbnbCereal_W_Md.otf",
})

export const metadata: Metadata = {
  title: "ziarah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${airbnbCereal.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
